// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIclupeNWEDx9wSv2k_GLTULnr8a2Pw5w',
    appId: '1:712410683340:web:321cc9864107944056af69',
    messagingSenderId: '712410683340',
    projectId: 'kupf-5fe2b',
    authDomain: 'kupf-5fe2b.firebaseapp.com',
    storageBucket: 'kupf-5fe2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ILkBnUcz_wEfiQiuYJGKHAs1g-VUQmI',
    appId: '1:712410683340:android:f571b48c1eb09c5256af69',
    messagingSenderId: '712410683340',
    projectId: 'kupf-5fe2b',
    storageBucket: 'kupf-5fe2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHOCEzL3bTSqq2RSQmIk8KhDbQCHQoNic',
    appId: '1:712410683340:ios:48a4ead6d359705656af69',
    messagingSenderId: '712410683340',
    projectId: 'kupf-5fe2b',
    storageBucket: 'kupf-5fe2b.appspot.com',
    androidClientId: '712410683340-fftgr20dq05lfj3203o5fbo55u9g3srd.apps.googleusercontent.com',
    iosClientId: '712410683340-2kkhuh9eah8dk8fi3dao2913j1dpfspc.apps.googleusercontent.com',
    iosBundleId: 'com.example.kupf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHOCEzL3bTSqq2RSQmIk8KhDbQCHQoNic',
    appId: '1:712410683340:ios:9cf0857113c7c53b56af69',
    messagingSenderId: '712410683340',
    projectId: 'kupf-5fe2b',
    storageBucket: 'kupf-5fe2b.appspot.com',
    androidClientId: '712410683340-fftgr20dq05lfj3203o5fbo55u9g3srd.apps.googleusercontent.com',
    iosClientId: '712410683340-rv8vg3apkhn9dla5ne592kupfqjk34iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.kupfMobile',
  );
}
